name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy-astro:
    name: Deploy Astro Site
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Build Astro Site
        run: npm ci && npm run build
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
